### ISSUE TITLE
Cache crates.io index for CI

### ISSUE THREAD

**Issue by wildwestrom** [fspoettel/advent-of-code-rust#23]
I decided [personally](https://github.com/wildwestrom/aoc-2022/blob/main/.github/workflows/ci.yml) it was a good idea to cache the crates.io index.

Do you think it's a good idea to do this for the template?
* A disadvantage is that the index (which is about 300MB) is now stored on Github's servers.
* An advantage is now the action doesn't have to fetch the entire crates.io index every time, which takes too long for my impatient self.

Example:
```yaml
            - uses: actions/cache@v3
              with:
                path: |
                    ~/.cargo/registry/index/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock')
```
